spring:
  config:
    import: "vault://"
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: auth-service
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token: ${VAULT_TOKEN}
      scheme: http
      kv:
        enabled: true
        kv-version: 2
      fail-fast: true
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

sentry:
  send-default-pii: true
  logs:
    enabled: true
    minimum-level: info
  tags:
    service: auth-service

springdoc:
  swagger-ui:
    path: /api/v1/tokens/swagger-ui
  api-docs:
    path: /api/v1/tokens/api-docs