spring:
  application:
    name: notification-service

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.web.socket.server: TRACE
    org.springframework.messaging.simp: TRACE