server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  server:
    port: 8092
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always