version: '3.7'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

  jaeger:
    image: jaegertracing/all-in-one:1.75.0
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources