scrape_configs:
  - job_name: "APIGateway"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    # tls_config:
    #   insecure_skip_verify: true
    # scheme: https
    static_configs:
      - targets: ["api_gateway:8085"]
        labels:
          application: "APIGateway"