spring:
  application:
    name: chat-service
  data:
    mongodb:
      host: ${MONGODB_HOST}
      database: chats
      port: 27017
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: ${MONGO_AUTH}

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

frontendUrl: http://localhost:5174/

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always