spring:
  application:
    name: chat-service

  config:
    import: "vault://"

  data:
    mongodb:
      host: ${MONGODB_HOST}
      database: chats
      port: ${MONGODB_PORT:27017}
      authentication-database: ${MONGO_AUTH}

  cloud:
    vault:
      uri: http://${VAULT_HOST:127.0.0.1}:8200
      token: ${VAULT_TOKEN}
      scheme: http
      kv:
        enabled: true
        kv-version: 2
      fail-fast: true

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_DISCOVERY_HOST}:8761/eureka
    instance:
      preferIpAddress: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

frontendUrl: http://localhost:5173

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

sentry:
  send-default-pii: true
  logs:
    enabled: true
    minimum-level: info
  tags:
    service: chat-service