name: social-network

services:
  vault:
    image: hashicorp/vault
    ports:
      - "8200:8200"
      - "8201:8201"
    volumes:
      - vault_data:/vault/data
      - ./vault/config:/etc/vault/config
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_API_ADDR=http://127.0.0.1:8200
      - SKIP_SETCAP=true
    cap_add:
      - IPC_LOCK

  posts-service-db:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - social_network_db_data:/var/lib/postgresql

  user-service-db:
    image: mysql:9.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - social_network_users_db_data:/var/lib/mysql

  kafka:
    image: apache/kafka:4.0.0
    hostname: kafka
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
    ports:
      - "9092:9092"
    volumes:
      - social_network_kafka_data:/tmp/kraft-combined-logs

  kafka-exporter:
    image: danielqsj/kafka-exporter
    command: ["--kafka.server=kafka:9092"]
    restart: on-failure
    ports:
      - "9308:9308"
    depends_on:
      - kafka

  redis:
    image: redis/redis-stack
    ports:
      - "6380:6379"
      - "8002:8001"

  chat-service-db:
    image: mongo:7
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - social_network_chat_db_data:/data/db

  service-discovery:
    build: ../service-discovery
    ports:
      - "8761:8761"

  api-gateway:
    build: ../api-gateway
    env_file: compose.env
    environment:
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - "8085:8085"
    depends_on:
      - service-discovery
      - redis

  auth-service:
    build: ../auth-service
    env_file: compose.env
    environment:
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      VAULT_HOST: ${VAULT_HOST}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - service-discovery
      - vault
      - redis

  post-service:
    build: ../post-service
    env_file: compose.env
    environment:
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      VAULT_HOST: ${VAULT_HOST}
      REDIS_HOST: ${REDIS_HOST}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      - service-discovery
      - vault
      - redis
      - posts-service-db

  user-service:
    build: ../user-service
    env_file: compose.env
    environment:
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      REDIS_HOST: ${REDIS_HOST}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - service-discovery
      - redis
      - user-service-db

  chat-service:
    build: ../chat-service
    env_file: compose.env
    environment:
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
    depends_on:
      - service-discovery
      - chat-service-db

  notification-service:
    build: ../notification-service
    env_file: compose.env
    environment:
      SERVICE_DISCOVERY_HOST: ${SERVICE_DISCOVERY_HOST}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - service-discovery
      - redis

volumes:
  vault_data:
  social_network_db_data:
  social_network_users_db_data:
  social_network_chat_db_data:
  social_network_kafka_data: