name: CI — user-service

on:
  push:
    branches: [main, dev]
    paths: ['user-service/**']
  pull_request:
    branches: [main, dev]
    paths: ['user-service/**']

jobs:
  build:
    uses: ./.github/workflows/_gradle-build.yml
    with:
      service: user-service
